CFLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

main.o: main.cpp
	g++ $(CFLAGS) -c main.cpp
stackFunctions.o: stackFunctions.cpp
	g++ $(CFLAGS) -c stackFunctions.cpp
Stack.exe: main.o stackFunctions.o
	g++ $(CFLAGS) main.o stackFunctions.o -o Stack
clean:
	rm main.o stackFunctions.o
build: Stack.exe
